export const UPDATE_STUDENT_LIST_PENDING = "student/UPDATE_STUDENT_LIST_PENDING";

export const UPDATE_STUDENT_LIST_FULFILLED = "student/UPDATE_STUDENT_LIST_FULFILLED";

export const UPDATE_STUDENT_LIST_REJECTED = "student/UPDATE_STUDENT_LIST_REJECTED";

export const UPDATE_SELECTED_STUDENT = "student/UPDATE_SELECTED_STUDENT";

export const UPDATE_SEARCH_TERM = "student/UPDATE_SEARCH_TERM";

